name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build via webhook
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          curl -X POST \
          -u "${JENKINS_USERNAME}:${JENKINS_API_TOKEN}" \
          "${JENKINS_URL}/job/flask-app-pipeline/buildWithParameters?token=YOUR_JENKINS_BUILD_TOKEN"
